services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_DATABASE: ${DB_DATABASE}
      TZ: UTC
      # Проверка и перезапуск контейнера при недоступности
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      #interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - '3306:3306'
    volumes:
      - inventory_db:/var/lib/mysql
    # networks:
    #   - internal_network

volumes:
  inventory_db:
# networks:
#   internal_network:
#     internal: true
