import { DataSource } from 'typeorm';
import { User } from '@Modules/user/entities/User';
import { Staff } from '@Modules/staff/entities/Staff';

export async function seedStaffs(dataSourse: DataSource) {
  const userRepo = dataSourse.getRepository(User);
  const staffRepo = dataSourse.getRepository(Staff);
  // Я не буду давать проверку на существование пользователей

  const systemUser = await userRepo.findOne({
    where: {
      username: 'system',
    },
    withDeleted: true,
  });

  const staffs = [
    {
      lastname: 'Авдасьева',
      name: 'Ирина',
      patronimyc: 'Витальевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Авраменко',
      name: 'Любовь',
      patronimyc: 'Алексеевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Айрапетян',
      name: 'Тамара',
      patronimyc: 'Айказовна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Аладина',
      name: 'Олеся',
      patronimyc: 'Геннадьевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Алексанян',
      name: 'Саркис',
      patronimyc: 'Жораевич',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Алексашин',
      name: 'Антон',
      patronimyc: 'Дмитриевич',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Амирова',
      name: 'Карина',
      patronimyc: 'Сергеевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Ананьева',
      name: 'Оксана',
      patronimyc: 'Сергеевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Апарина',
      name: 'Елена',
      patronimyc: 'Владимировна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Апарина',
      name: 'Ирина',
      patronimyc: 'Александровна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Артеменко',
      name: 'Наталия',
      patronimyc: 'Юрьевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Ахмедова',
      name: 'Аида',
      patronimyc: 'Дамир Кызы',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Ашнокова',
      name: 'Инесса',
      patronimyc: 'Викторовна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Байтиков',
      name: 'Улан',
      patronimyc: 'Турдакунович',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Балоян',
      name: 'Алина',
      patronimyc: 'Валиковна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Баранова',
      name: 'Ольга',
      patronimyc: 'Владимировна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Басавина',
      name: 'Ирина',
      patronimyc: 'Анатольевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Бобров',
      name: 'Сергей',
      patronimyc: 'Иванович',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Богатырева',
      name: 'Мариам',
      patronimyc: 'Махмудовна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Богосян',
      name: 'Валентина',
      patronimyc: 'Павловна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Бойкова',
      name: 'Ирина',
      patronimyc: 'Сергеевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Брусенский',
      name: 'Михаил',
      patronimyc: 'Валерьевич',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Брусникина',
      name: 'Нина',
      patronimyc: 'Владимировна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Булимова',
      name: 'Елена',
      patronimyc: 'Владимировна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Бутаева',
      name: 'Альбина',
      patronimyc: 'Валерьевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Быкова',
      name: 'Наталья',
      patronimyc: 'Борисовна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Валентова',
      name: 'Екатерина',
      patronimyc: 'Игоревна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Варзарева',
      name: 'Анастасия',
      patronimyc: 'Евгеньевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Вилкина',
      name: 'Татьяна',
      patronimyc: '',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Винокурова',
      name: 'Лариса',
      patronimyc: 'Луновна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Вирченко',
      name: 'Станислав',
      patronimyc: 'Валерьевич',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Вишневецкая',
      name: 'Людмила',
      patronimyc: 'Сергеевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Влондис',
      name: 'Игорь',
      patronimyc: 'Олегович',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Влондис',
      name: 'Ольга',
      patronimyc: 'Олеговна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Воронецкая',
      name: 'Светлана',
      patronimyc: 'Васильевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Воронина',
      name: 'Лариса',
      patronimyc: 'Геннадьевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Воротынцев',
      name: 'Алексей',
      patronimyc: 'Сергеевич',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Воскресенская',
      name: 'Лариса',
      patronimyc: 'Евгеньевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Габелия',
      name: 'Георгий',
      patronimyc: 'Рубенович',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Гальченко',
      name: 'Максим',
      patronimyc: 'Юрьевич',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Гаричкина',
      name: 'Марина',
      patronimyc: 'Николаевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Гогилов',
      name: 'Петр',
      patronimyc: 'Николаевич',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Голяндр',
      name: 'Татьяна',
      patronimyc: 'Ивановна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Гомзяк',
      name: 'Марина',
      patronimyc: 'Евгеньевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Гончарова',
      name: 'Оксана',
      patronimyc: 'Сергеевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Гордон',
      name: 'Кирилл',
      patronimyc: 'Владиславович',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Горяинова',
      name: 'Анастасия',
      patronimyc: 'Михайловна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Гринева',
      name: 'Ольга',
      patronimyc: 'Владимировна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Гугулян',
      name: 'Эмма',
      patronimyc: 'Акоповна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Гупта',
      name: 'Майанк',
      patronimyc: '',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Данелян',
      name: 'Лида',
      patronimyc: 'Ованесовна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Данилевская',
      name: 'Инна',
      patronimyc: 'Владимировна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Данилюк',
      name: 'Елена',
      patronimyc: 'Павловна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Дарсания',
      name: 'Зураб',
      patronimyc: 'Вахтангиевич',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Денисенко',
      name: 'Татьяна',
      patronimyc: 'Михайловна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Денщик',
      name: 'Иван',
      patronimyc: 'Васильевич',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Долецкая',
      name: 'Индеана',
      patronimyc: 'Георгиевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Дорохова',
      name: 'Надежда',
      patronimyc: 'Петровна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Дунаев',
      name: 'Илья',
      patronimyc: 'Алексеевич',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Дунько',
      name: 'Антон',
      patronimyc: 'Анатольевич',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Дунько',
      name: 'Глеб',
      patronimyc: 'Анатольевич',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Дюдина',
      name: 'Елизавета',
      patronimyc: 'Сергеевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Евдокимова',
      name: 'Ольга',
      patronimyc: 'Константиновна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Емельянова',
      name: 'Ирина',
      patronimyc: 'Алексеевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Еременко',
      name: 'Эрика',
      patronimyc: 'Яковлевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Ждамирова',
      name: 'Инна',
      patronimyc: 'Викторовна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Жулина',
      name: 'Екатерина',
      patronimyc: 'Юрьевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Зантария',
      name: 'Астанда',
      patronimyc: 'Степановна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Захарьян',
      name: 'Рубен',
      patronimyc: 'Арменакович',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Ильменев',
      name: 'Генрих',
      patronimyc: 'Олегович',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Казюленко',
      name: 'Алексей',
      patronimyc: 'Александрович',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Календжян',
      name: 'Анна',
      patronimyc: 'Овагимовна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Карлина',
      name: 'Оксана',
      patronimyc: 'Васильевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Карсанова',
      name: 'Лилия',
      patronimyc: 'Артемовна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Катенева',
      name: 'Татьяна',
      patronimyc: 'Васильевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Керефова',
      name: 'Дарина',
      patronimyc: 'Руслановна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Кириченко',
      name: 'Ольга',
      patronimyc: 'Викторовна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Кныш',
      name: 'Ольга',
      patronimyc: 'Николаевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Ковалева',
      name: 'Эльза',
      patronimyc: 'Гайнановна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Кованкина',
      name: 'Наталья',
      patronimyc: 'Александровна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Колмыченко',
      name: 'Лариса',
      patronimyc: 'Викторовна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Коренев',
      name: 'Игорь',
      patronimyc: 'Иванович',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Король',
      name: 'Ольга',
      patronimyc: 'Анатольевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Костина',
      name: 'Валентина',
      patronimyc: 'Викторовна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Кравцов',
      name: 'Павел',
      patronimyc: 'Викторович',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Крашилина',
      name: 'Марина',
      patronimyc: 'Александровна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Кузина',
      name: 'Ксения',
      patronimyc: 'Алексеевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Кузнецова',
      name: 'Анна',
      patronimyc: 'Александровна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Кулумбегова',
      name: 'Татьяна',
      patronimyc: 'Арамовна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Купченко',
      name: 'Розия',
      patronimyc: 'Габдулбариевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Кучерова',
      name: 'Елена',
      patronimyc: 'Григорьевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Ларионов',
      name: 'Денис',
      patronimyc: 'Владиславович',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Леусенко',
      name: 'Елена',
      patronimyc: 'Викторовна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Лисанская',
      name: 'Мария',
      patronimyc: 'Романовна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Лисоченко',
      name: 'Юлия',
      patronimyc: 'Ивановна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Лысогор',
      name: 'Лариса',
      patronimyc: 'Евгеньевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Любимова',
      name: 'Ксения',
      patronimyc: 'Владимировна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Магамадова',
      name: 'Элиза',
      patronimyc: 'Алимхановна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Магомедова',
      name: 'Виктория',
      patronimyc: 'Вячеславовна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Майорова',
      name: 'Виктория',
      patronimyc: 'Викторовна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Максименко',
      name: 'Зоя',
      patronimyc: 'Сергеевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Малик',
      name: 'Надежда',
      patronimyc: 'Леонидовна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Матвеев',
      name: 'Марк',
      patronimyc: 'Валериевич',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Махаури',
      name: 'Макка',
      patronimyc: 'Хамзатовна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Маценко',
      name: 'Борис',
      patronimyc: 'Михайлович',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Мелехина',
      name: 'Инесса',
      patronimyc: 'Андреевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Мелик-Степанян',
      name: 'Жанна',
      patronimyc: 'Григорьевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Моисеенко',
      name: 'Евгения',
      patronimyc: 'Игоревна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Моисейшина',
      name: 'Наталья',
      patronimyc: 'Сергеевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Мухамедьянов',
      name: 'Гайсар',
      patronimyc: 'Саматович',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Мышланов',
      name: 'Валентин',
      patronimyc: 'Иванович',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Наливайко',
      name: 'Александр',
      patronimyc: 'Вадимович',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Нечаев',
      name: 'Михаил',
      patronimyc: 'Николаевич',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Нечаева',
      name: 'Елена',
      patronimyc: 'Сергеевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Овсепьян',
      name: 'Татьяна',
      patronimyc: 'Саркисовна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Овчаренко',
      name: 'Елена',
      patronimyc: 'Михайловна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Оранская',
      name: 'Татьяна',
      patronimyc: 'Юрьевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Орехова',
      name: 'Елена',
      patronimyc: 'Ивановна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Осипян',
      name: 'Яна',
      patronimyc: 'Семёновна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Павленко',
      name: 'Алла',
      patronimyc: 'Арсеньевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Павленко',
      name: 'Анна',
      patronimyc: 'Андреевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Павлова',
      name: 'Нази',
      patronimyc: 'Камбизовна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Петров',
      name: 'Александр',
      patronimyc: 'Семенович',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Полищук',
      name: 'Валерия',
      patronimyc: 'Ивановна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Полунина',
      name: 'Бэлла',
      patronimyc: 'Семеновна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Попов',
      name: 'Антон',
      patronimyc: 'Викторович',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Рудакова',
      name: 'Оксана',
      patronimyc: 'Васильевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Румянцева',
      name: 'Ксения',
      patronimyc: 'Олеговна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Рыжова',
      name: 'Сусанна',
      patronimyc: 'Хачиковна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Савин',
      name: 'Сергей',
      patronimyc: 'Анатольевич',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Самарина',
      name: 'Ирина',
      patronimyc: 'Викторовна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Сариева',
      name: 'Анна',
      patronimyc: 'Викторовна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Сердюков',
      name: 'Василий',
      patronimyc: 'Васильевич',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Сержанова',
      name: 'Елена',
      patronimyc: 'Николаевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Скорикова',
      name: 'Ольга',
      patronimyc: 'Александровна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Снегирёв',
      name: 'Юрий',
      patronimyc: 'Николаевич',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Снесарева',
      name: 'Виктория',
      patronimyc: 'Владимировна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Соловьева',
      name: 'Любовь',
      patronimyc: 'Николаевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Сопкова',
      name: 'Валентина',
      patronimyc: 'Геннадьевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Степанова',
      name: 'Альбина',
      patronimyc: 'Герасимовна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Супрунова',
      name: 'Анна',
      patronimyc: 'Викторовна',
      financiallyResponsiblePerson: true,
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Суровикина',
      name: 'Ирина',
      patronimyc: 'Владимировна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Суханова',
      name: 'Марина',
      patronimyc: 'Валерьевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Талалаев',
      name: 'Сергей',
      patronimyc: 'Федорович',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Тарасова',
      name: 'Лиззет',
      patronimyc: 'Уменовна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Татаринова',
      name: 'Ирина',
      patronimyc: 'Венгисовна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Ткаченко',
      name: 'Наталья',
      patronimyc: 'Владимировна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Ткаченко',
      name: 'Олеся',
      patronimyc: 'Александровна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Товмасян',
      name: 'Наталья',
      patronimyc: 'Анатольевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Тухватшин',
      name: 'Рустэм',
      patronimyc: 'Фаритович',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Усова',
      name: 'Татьяна',
      patronimyc: 'Юрьевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Федорова',
      name: 'Татьяна',
      patronimyc: 'Викторовна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Хамалян',
      name: 'Ашот',
      patronimyc: 'Заренович',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Хамалян',
      name: 'Илона',
      patronimyc: 'Александровна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Хачатрян',
      name: 'Кристина',
      patronimyc: 'Араиковна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Холодён',
      name: 'Владимир',
      patronimyc: 'Алексеевич',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Храпалева',
      name: 'Анна',
      patronimyc: 'Ивановна',
      financiallyResponsiblePerson: true,
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Худайберганов',
      name: 'Давлат',
      patronimyc: 'Саидович',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Цабрия',
      name: 'Мимоза',
      patronimyc: 'Николаевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Чакрян',
      name: 'Сергей',
      patronimyc: 'Андроникович',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Чаплыгина',
      name: 'Кристина',
      patronimyc: 'Юрьевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Чернова',
      name: 'Наталья',
      patronimyc: 'Геннадьевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Чувилин',
      name: 'Дмитрий',
      patronimyc: 'Вячеславович',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Шаврина',
      name: 'Светлана',
      patronimyc: 'Владимировна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Шайдевич',
      name: 'Марина',
      patronimyc: 'Игоревна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Шарапов',
      name: 'Алексей',
      patronimyc: 'Васильевич',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Шахрудинова',
      name: 'Заира',
      patronimyc: 'Кадиевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Шевченко',
      name: 'Светлана',
      patronimyc: 'Алексеевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Шевчук',
      name: 'Марина',
      patronimyc: 'Павловна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Шелеметьева',
      name: 'Елена',
      patronimyc: 'Александровна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Шершнев',
      name: 'Станислав',
      patronimyc: 'Владимирович',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Шкиль',
      name: 'Павел',
      patronimyc: 'Викторович',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Шмалий',
      name: 'Анна',
      patronimyc: 'Викторовна',
      financiallyResponsiblePerson: true,
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Шмаргун',
      name: 'Ирина',
      patronimyc: 'Алексеевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Штаба',
      name: 'Петр',
      patronimyc: 'Афанасьевич',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Штанченко',
      name: 'Елена',
      patronimyc: 'Васильевна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Шульженко',
      name: 'Татьяна',
      patronimyc: 'Ивановна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Югай',
      name: 'Марина',
      patronimyc: 'Валентиновна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Яковлева',
      name: 'Ольга',
      patronimyc: 'Викторовна',
      creator: { id: systemUser?.id },
    },
    {
      lastname: 'Яхина',
      name: 'Альбина',
      patronimyc: 'Явитовна',
      creator: { id: systemUser?.id },
    },
  ];

  await staffRepo.insert(staffs);
  console.log('Персонал успешно создан');
}
