import { DataSource } from 'typeorm';
import * as bcrypt from 'bcrypt';
import { Role } from '@Modules/role/entities/Role';
import { User } from '@Modules/user/entities/User';
import { UserStatus } from '@common/enums/UserStatus';
import { Division } from '@Modules/division/entities/Division';

export async function seedUsers(dataSourse: DataSource) {
  const roleRepo = dataSourse.getRepository(Role);
  const userRepo = dataSourse.getRepository(User);
  const divisionRepo = dataSourse.getRepository(Division);
  const salt = await bcrypt.genSalt(10);
  // Я не буду давать проверку на существование пользователей

  const systemUser = await userRepo.findOneBy({ role: { roleName: 'system' } });

  const adminRole = await roleRepo.findOneBy({ roleName: 'admin' });

  //нужно уточнить как зовут сестер хоязек
  const userRole = await roleRepo.findOneBy({ roleName: 'user' });
  const staffRole = await roleRepo.findOneBy({ roleName: 'staff' });
  const divisionsId = await divisionRepo.find({ select: { id: true } });

  divisionsId.map((item) => (item.id === 1 ? item.id : null));

  const users = [
    {
      username: 'OinkOink',
      password: await bcrypt.hash('K4bJ99cK8', salt),
      name: 'Эдуард',
      lastname: 'Селедцов',
      patronimyc: 'Игоревич',
      telephone: '+79528360642',
      state: UserStatus.ACTIVE,
      role: { id: adminRole?.id },
      division: divisionsId,
      creator: { id: systemUser?.id },
    },
    {
      username: 'Palich',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Олег',
      lastname: 'Сидоренко',
      patronimyc: 'Павлович',
      telephone: '+79649403535',
      state: UserStatus.ACTIVE,
      role: { id: adminRole?.id },
      division: divisionsId,
      creator: { id: systemUser?.id },
    },
    {
      username: 'Punker',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Максим',
      lastname: 'Корытин',
      patronimyc: 'Сергеевич',
      telephone: '+79628885162',
      state: UserStatus.ACTIVE,
      role: { id: adminRole?.id },
      division: divisionsId,
      creator: { id: systemUser?.id },
    },
    {
      username: 'Nachalnik',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Егор',
      lastname: 'Аленин',
      patronimyc: 'Сергеевич',
      telephone: '+79180999888',
      state: UserStatus.ACTIVE,
      role: { id: adminRole?.id },
      division: divisionsId,
      creator: { id: systemUser?.id },
    },
    {
      username: 'avdasevai',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Ирина',
      lastname: 'Авдасьева',
      patronimyc: 'Витальевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'avramenkol',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Любовь',
      lastname: 'Авраменко',
      patronimyc: 'Алексеевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'ayrapetyant',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Тамара',
      lastname: 'Айрапетян',
      patronimyc: 'Айказовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'aladinao',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Олеся',
      lastname: 'Аладина',
      patronimyc: 'Геннадьевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'aleksanyans',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Саркис',
      lastname: 'Алексанян',
      patronimyc: 'Жораевич',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'alekshashina',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Антон',
      lastname: 'Алексашин',
      patronimyc: 'Дмитриевич',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'amirovak',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Карина',
      lastname: 'Амирова',
      patronimyc: 'Сергеевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'ananevao',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Оксана',
      lastname: 'Ананьева',
      patronimyc: 'Сергеевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'aparinae',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Елена',
      lastname: 'Апарина',
      patronimyc: 'Владимировна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'aparinai',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Ирина',
      lastname: 'Апарина',
      patronimyc: 'Александровна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'artemenkon',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Наталия',
      lastname: 'Артеменко',
      patronimyc: 'Юрьевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: userRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'akhmedovaa',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Аида',
      lastname: 'Ахмедова',
      patronimyc: 'Дамир Кызы',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'ashnokovai',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Инесса',
      lastname: 'Ашнокова',
      patronimyc: 'Викторовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'baytikova',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Улан',
      lastname: 'Байтиков',
      patronimyc: 'Турдакунович',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'baloyana',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Алина',
      lastname: 'Балоян',
      patronimyc: 'Валиковна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'baranovao',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Ольга',
      lastname: 'Баранова',
      patronimyc: 'Владимировна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'basavinai',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Ирина',
      lastname: 'Басавина',
      patronimyc: 'Анатольевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'bobrovs',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Сергей',
      lastname: 'Бобров',
      patronimyc: 'Иванович',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'bogatyrevam',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Мариам',
      lastname: 'Богатырева',
      patronimyc: 'Махмудовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'bogosyanv',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Валентина',
      lastname: 'Богосян',
      patronimyc: 'Павловна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'boykovai',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Ирина',
      lastname: 'Бойкова',
      patronimyc: 'Сергеевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'brusenskim',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Михаил',
      lastname: 'Брусенский',
      patronimyc: 'Валерьевич',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'brusnikinan',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Нина',
      lastname: 'Брусникина',
      patronimyc: 'Владимировна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'bulimovae',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Елена',
      lastname: 'Булимова',
      patronimyc: 'Владимировна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'butaevaa',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Альбина',
      lastname: 'Бутаева',
      patronimyc: 'Валерьевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'bykovan',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Наталья',
      lastname: 'Быкова',
      patronimyc: 'Борисовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'valentovae',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Екатерина',
      lastname: 'Валентова',
      patronimyc: 'Игоревна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'varzarevaa',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Анастасия',
      lastname: 'Варзарева',
      patronimyc: 'Евгеньевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'vilkinat',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Татьяна',
      lastname: 'Вилкина',
      patronimyc: '',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'vinokuroval',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Лариса',
      lastname: 'Винокурова',
      patronimyc: 'Луновна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'virchenkos',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Станислав',
      lastname: 'Вирченко',
      patronimyc: 'Валерьевич',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'vishnevetskayal',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Людмила',
      lastname: 'Вишневецкая',
      patronimyc: 'Сергеевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'vlondisi',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Игорь',
      lastname: 'Влондис',
      patronimyc: 'Олегович',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'vlondiso',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Ольга',
      lastname: 'Влондис',
      patronimyc: 'Олеговна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'voronetskayas',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Светлана',
      lastname: 'Воронецкая',
      patronimyc: 'Васильевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'voroninal',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Лариса',
      lastname: 'Воронина',
      patronimyc: 'Геннадьевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'vorotyntseva',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Алексей',
      lastname: 'Воротынцев',
      patronimyc: 'Сергеевич',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'voskresenskayal',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Лариса',
      lastname: 'Воскресенская',
      patronimyc: 'Евгеньевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 1 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'gabeliyag',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Георгий',
      lastname: 'Габелия',
      patronimyc: 'Рубенович',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'galchenkom',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Максим',
      lastname: 'Гальченко',
      patronimyc: 'Юрьевич',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'garichkinam',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Марина',
      lastname: 'Гаричкина',
      patronimyc: 'Николаевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'gogilovp',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Петр',
      lastname: 'Гогилов',
      patronimyc: 'Николаевич',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'golyandrt',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Татьяна',
      lastname: 'Голяндр',
      patronimyc: 'Ивановна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'gomzyakm',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Марина',
      lastname: 'Гомзяк',
      patronimyc: 'Евгеньевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'goncharovao',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Оксана',
      lastname: 'Гончарова',
      patronimyc: 'Сергеевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'gordonk',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Кирилл',
      lastname: 'Гордон',
      patronimyc: 'Владиславович',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'goryainovaa',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Анастасия',
      lastname: 'Горяинова',
      patronimyc: 'Михайловна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'grinevao',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Ольга',
      lastname: 'Гринева',
      patronimyc: 'Владимировна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: userRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'gugulyane',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Эмма',
      lastname: 'Гугулян',
      patronimyc: 'Акоповна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'guptam',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Майанк',
      lastname: 'Гупта',
      patronimyc: '',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'danelyanl',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Лида',
      lastname: 'Данелян',
      patronimyc: 'Ованесовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'danilevskayai',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Инна',
      lastname: 'Данилевская',
      patronimyc: 'Владимировна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'danilyuke',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Елена',
      lastname: 'Данилюк',
      patronimyc: 'Павловна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'darsaniyaz',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Зураб',
      lastname: 'Дарсания',
      patronimyc: 'Вахтангиевич',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'denisenkot',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Татьяна',
      lastname: 'Денисенко',
      patronimyc: 'Михайловна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'denshchiki',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Иван',
      lastname: 'Денщик',
      patronimyc: 'Васильевич',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'doletskayai',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Индеана',
      lastname: 'Долецкая',
      patronimyc: 'Георгиевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'dorokhovan',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Надежда',
      lastname: 'Дорохова',
      patronimyc: 'Петровна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'dunaevi',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Илья',
      lastname: 'Дунаев',
      patronimyc: 'Алексеевич',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'dunkoa',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Антон',
      lastname: 'Дунько',
      patronimyc: 'Анатольевич',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'dunkog',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Глеб',
      lastname: 'Дунько',
      patronimyc: 'Анатольевич',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'dyudinae',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Елизавета',
      lastname: 'Дюдина',
      patronimyc: 'Сергеевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'evdokimova',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Ольга',
      lastname: 'Евдокимова',
      patronimyc: 'Константиновна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'emelyanovai',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Ирина',
      lastname: 'Емельянова',
      patronimyc: 'Алексеевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'eremenkoe',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Эрика',
      lastname: 'Еременко',
      patronimyc: 'Яковлевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'zh damirovai',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Инна',
      lastname: 'Ждамирова',
      patronimyc: 'Викторовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'zhuline',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Екатерина',
      lastname: 'Жулина',
      patronimyc: 'Юрьевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'zantariyaa',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Астанда',
      lastname: 'Зантария',
      patronimyc: 'Степановна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'zakharyanr',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Рубен',
      lastname: 'Захарьян',
      patronimyc: 'Арменакович',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'ilmenevg',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Генрих',
      lastname: 'Ильменев',
      patronimyc: 'Олегович',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'kazyulenkoa',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Алексей',
      lastname: 'Казюленко',
      patronimyc: 'Александрович',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'kalendzhyana',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Анна',
      lastname: 'Календжян',
      patronimyc: 'Овагимовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'karlinao',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Оксана',
      lastname: 'Карлина',
      patronimyc: 'Васильевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'karsanoval',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Лилия',
      lastname: 'Карсанова',
      patronimyc: 'Артемовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'katenevat',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Татьяна',
      lastname: 'Катенева',
      patronimyc: 'Васильевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'kerefovad',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Дарина',
      lastname: 'Керефова',
      patronimyc: 'Руслановна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'kirichenkoo',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Ольга',
      lastname: 'Кириченко',
      patronimyc: 'Викторовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'knysho',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Ольга',
      lastname: 'Кныш',
      patronimyc: 'Николаевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'kovalevae',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Эльза',
      lastname: 'Ковалева',
      patronimyc: 'Гайнановна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'kovankinan',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Наталья',
      lastname: 'Кованкина',
      patronimyc: 'Александровна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'kolmychenkol',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Лариса',
      lastname: 'Колмыченко',
      patronimyc: 'Викторовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'korenevi',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Игорь',
      lastname: 'Коренев',
      patronimyc: 'Иванович',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'korolo',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Ольга',
      lastname: 'Король',
      patronimyc: 'Анатольевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'kostinav',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Валентина',
      lastname: 'Костина',
      patronimyc: 'Викторовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 2 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'kravtsovp',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Павел',
      lastname: 'Кравцов',
      patronimyc: 'Викторович',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'krasilinam',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Марина',
      lastname: 'Крашилина',
      patronimyc: 'Александровна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'kuzinak',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Ксения',
      lastname: 'Кузина',
      patronimyc: 'Алексеевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'kuznetsovaa',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Анна',
      lastname: 'Кузнецова',
      patronimyc: 'Александровна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'kulumbegovat',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Татьяна',
      lastname: 'Кулумбегова',
      patronimyc: 'Арамовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'kupchenkor',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Розия',
      lastname: 'Купченко',
      patronimyc: 'Габдулбариевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'kucherovae',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Елена',
      lastname: 'Кучерова',
      patronimyc: 'Григорьевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'larionovd',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Денис',
      lastname: 'Ларионов',
      patronimyc: 'Владиславович',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'leusenkoe',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Елена',
      lastname: 'Леусенко',
      patronimyc: 'Викторовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'lisanskayam',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Мария',
      lastname: 'Лисанская',
      patronimyc: 'Романовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'lisochenkoy',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Юлия',
      lastname: 'Лисоченко',
      patronimyc: 'Ивановна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'lysogorl',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Лариса',
      lastname: 'Лысогор',
      patronimyc: 'Евгеньевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: userRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'lyubimovak',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Ксения',
      lastname: 'Любимова',
      patronimyc: 'Владимировна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'magamadovae',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Элиза',
      lastname: 'Магамадова',
      patronimyc: 'Алимхановна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'magomedovav',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Виктория',
      lastname: 'Магомедова',
      patronimyc: 'Вячеславовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'mayorovav',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Виктория',
      lastname: 'Майорова',
      patronimyc: 'Викторовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'maksimenkoz',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Зоя',
      lastname: 'Максименко',
      patronimyc: 'Сергеевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'malikn',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Надежда',
      lastname: 'Малик',
      patronimyc: 'Леонидовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'matveevm',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Марк',
      lastname: 'Матвеев',
      patronimyc: 'Валериевич',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'makhaurim',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Макка',
      lastname: 'Махаури',
      patronimyc: 'Хамзатовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'matsenkob',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Борис',
      lastname: 'Маценко',
      patronimyc: 'Михайлович',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'melekhinai',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Инесса',
      lastname: 'Мелехина',
      patronimyc: 'Андреевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'melik-stepanyang',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Жанна',
      lastname: 'Мелик-Степанян',
      patronimyc: 'Григорьевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'moiseenkoe',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Евгения',
      lastname: 'Моисеенко',
      patronimyc: 'Игоревна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'moiseyshinan',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Наталья',
      lastname: 'Моисейшина',
      patronimyc: 'Сергеевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'mukhamedyanovg',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Гайсар',
      lastname: 'Мухамедьянов',
      patronimyc: 'Саматович',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'myshlanovv',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Валентин',
      lastname: 'Мышланов',
      patronimyc: 'Иванович',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'nalivaykoa',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Александр',
      lastname: 'Наливайко',
      patronimyc: 'Вадимович',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'nechaevm',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Михаил',
      lastname: 'Нечаев',
      patronimyc: 'Николаевич',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'nechaevae',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Елена',
      lastname: 'Нечаева',
      patronimyc: 'Сергеевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'ovsepyant',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Татьяна',
      lastname: 'Овсепьян',
      patronimyc: 'Саркисовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'ovcherenkoe',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Елена',
      lastname: 'Овчаренко',
      patronimyc: 'Михайловна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'oranskayat',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Татьяна',
      lastname: 'Оранская',
      patronimyc: 'Юрьевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'orekhovae',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Елена',
      lastname: 'Орехова',
      patronimyc: 'Ивановна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'osipyany',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Яна',
      lastname: 'Осипян',
      patronimyc: 'Семёновна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'pavlenkoa',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Алла',
      lastname: 'Павленко',
      patronimyc: 'Арсеньевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'pavlenkoan',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Анна',
      lastname: 'Павленко',
      patronimyc: 'Андреевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'pavlovn',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Нази',
      lastname: 'Павлова',
      patronimyc: 'Камбизовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'petrova',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Александр',
      lastname: 'Петров',
      patronimyc: 'Семенович',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'polishchukv',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Валерия',
      lastname: 'Полищук',
      patronimyc: 'Ивановна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'poluninab',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Бэлла',
      lastname: 'Полунина',
      patronimyc: 'Семеновна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'popova',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Антон',
      lastname: 'Попов',
      patronimyc: 'Викторович',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'rudakovao',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Оксана',
      lastname: 'Рудакова',
      patronimyc: 'Васильевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'rumyantsevak',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Ксения',
      lastname: 'Румянцева',
      patronimyc: 'Олеговна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'ryzhovas',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Сусанна',
      lastname: 'Рыжова',
      patronimyc: 'Хачиковна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'savins',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Сергей',
      lastname: 'Савин',
      patronimyc: 'Анатольевич',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'samarina',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Ирина',
      lastname: 'Самарина',
      patronimyc: 'Викторовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'sarievaa',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Анна',
      lastname: 'Сариева',
      patronimyc: 'Викторовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'serdyukovv',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Василий',
      lastname: 'Сердюков',
      patronimyc: 'Васильевич',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'serzhanovae',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Елена',
      lastname: 'Сержанова',
      patronimyc: 'Николаевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'skorikovao',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Ольга',
      lastname: 'Скорикова',
      patronimyc: 'Александровна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'snegirevy',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Юрий',
      lastname: 'Снегирёв',
      patronimyc: 'Николаевич',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'snesarevav',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Виктория',
      lastname: 'Снесарева',
      patronimyc: 'Владимировна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 3 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'solovyeval',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Любовь',
      lastname: 'Соловьева',
      patronimyc: 'Николаевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 4 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'sopkovav',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Валентина',
      lastname: 'Сопкова',
      patronimyc: 'Геннадьевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 4 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'stepanovaa',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Альбина',
      lastname: 'Степанова',
      patronimyc: 'Герасимовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 4 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'suprunovaa',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Анна',
      lastname: 'Супрунова',
      patronimyc: 'Викторовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 4 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'surovikinai',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Ирина',
      lastname: 'Суровикина',
      patronimyc: 'Владимировна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 4 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'sukhanovam',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Марина',
      lastname: 'Суханова',
      patronimyc: 'Валерьевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: userRole?.id },
      division: [{ id: 4 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'talalaevs',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Сергей',
      lastname: 'Талалаев',
      patronimyc: 'Федорович',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 4 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'tarasoval',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Лиззет',
      lastname: 'Тарасова',
      patronimyc: 'Уменовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 4 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'tatarinovai',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Ирина',
      lastname: 'Татаринова',
      patronimyc: 'Венгисовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 4 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'tkachenkon',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Наталья',
      lastname: 'Ткаченко',
      patronimyc: 'Владимировна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 4 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'tkachenkoo',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Олеся',
      lastname: 'Ткаченко',
      patronimyc: 'Александровна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 4 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'tovmasyann',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Наталья',
      lastname: 'Товмасян',
      patronimyc: 'Анатольевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 4 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'tukhvatshinr',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Рустэм',
      lastname: 'Тухватшин',
      patronimyc: 'Фаритович',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 4 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'usovat',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Татьяна',
      lastname: 'Усова',
      patronimyc: 'Юрьевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 4 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'fedorovat',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Татьяна',
      lastname: 'Федорова',
      patronimyc: 'Викторовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 4 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'khamalyana',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Анна',
      lastname: 'Хамалян',
      patronimyc: 'Карапетовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 4 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'kharitonovas',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Светлана',
      lastname: 'Харитонова',
      patronimyc: 'Васильевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 4 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'khasanovar',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Рената',
      lastname: 'Хасанова',
      patronimyc: 'Радиковна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 4 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'khrapalevaa',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Анна',
      lastname: 'Храпалева',
      patronimyc: 'Вячеславовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 4 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'tsaturyang',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Гаяне',
      lastname: 'Цатурян',
      patronimyc: 'Грачьяевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 4 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'chepigan',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Наталья',
      lastname: 'Чепига',
      patronimyc: 'Викторовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 4 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'chernyavskayam',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Марина',
      lastname: 'Чернявская',
      patronimyc: 'Валерьевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 4 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'shaydullinal',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Лилия',
      lastname: 'Шайдуллина',
      patronimyc: 'Равильевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 4 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'shalaginaa',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Анна',
      lastname: 'Шалагина',
      patronimyc: 'Валерьевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 4 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'shestakovae',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Елена',
      lastname: 'Шестакова',
      patronimyc: 'Валерьевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 4 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'shmaliya',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Анна',
      lastname: 'Шмалий',
      patronimyc: 'Васильевна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 4 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'yudinae',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Елена',
      lastname: 'Юдина',
      patronimyc: 'Викторовна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 4 }],
      creator: { id: systemUser?.id },
    },
    {
      username: 'yusupovay',
      password: await bcrypt.hash('q1w2e3r4t5y6', salt),
      name: 'Юлия',
      lastname: 'Юсупова',
      patronimyc: 'Радиковна',
      telephone: '+333333333333',
      state: UserStatus.ACTIVE,
      role: { id: staffRole?.id },
      division: [{ id: 4 }],
      creator: { id: systemUser?.id },
    },
  ];

  await userRepo.save(users);
  console.log('Пользователи успешно созданы');

  await roleRepo.update({}, { creator: { id: systemUser?.id } });
  console.log('Ролям добавлен создатель system');
}
